sudo: true
language: node_js
node_js:
  - "6"
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
before_script:
  - npm install -g truffle
  - npm run testrpc > testrpc.log &
after_script:
  - cat testrpc.log
